volumes:
  data:

services:
  postgres:
    image: postgres:latest
    environment:
      - .evn
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql
  myapp:
    image:postgres-anGT

