version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 55001:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d

